# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
